package typegen

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"unicode"
)

func GenerateTypeDef(parent TsType, export bool) string {
	types := parent.Properties
	var writer strings.Builder
	if export {
		writer.WriteString("export ")
	}
	writer.WriteString(fmt.Sprintf("type %s = {\n", parent.Ident))
	for _, v := range types {
		writer.WriteString("\t")
		writer.WriteString(v.Name)
		if v.Optional {
			writer.WriteString("?")
		}
		writer.WriteString(": ")
		if v.Kind == Struct {
			writer.WriteString(v.Ident.String())
		} else if v.Kind == Array {
			writer.WriteString(fmt.Sprintf("%s[]", v.Elem().Ident))
		} else if v.Kind == Map {
			writer.WriteString("{\n")
			writer.WriteString(fmt.Sprintf("\t\t[key: %s]: ", v.MapKey().Ident))
			writer.WriteString(v.Elem().Ident.String())
			if v.Elem().Optional {
				writer.WriteString(" | null")
			}
			writer.WriteString(";\n")
			writer.WriteString("\t}")
		} else if v.Kind == Primitive {
			writer.WriteString(v.Ident.String())
		} else {
			writer.WriteString("never")
		}
		writer.WriteString(";\n")
	}

	writer.WriteString("}")
	writer.WriteString("\n")

	return writer.String()
}

func GenerateTypeScriptForComponent(typeDir string, component string, props map[string]any, optionals []string) error {
	types, err := ConvertMap(props)
	if err != nil {
		return fmt.Errorf("ConvertMap: %w", err)
	}
	componentName, err := FormatComponentName(component)
	if err != nil {
		return fmt.Errorf("formatting component name: %w", err)
	}

	componentName = fmt.Sprintf("%sProps", componentName)
	var typesWithOptionals []TsType

	for _, t := range types {
		if slices.Contains(optionals, t.Name) {
			t.Optional = true
		}
		typesWithOptionals = append(typesWithOptionals, t)
	}

	types = typesWithOptionals

	typeDefCache := make(identCache)
	typeDefCache[Ident(componentName)] = types
	getTypeDefs(typeDefCache, types)

	// sort alphabetically
	var typeDefs []TsType
	for ident, subTypes := range typeDefCache {
		typ := NewRootType(ident, subTypes)
		typeDefs = append(typeDefs, typ)
	}

	sort.Slice(typeDefs, func(i, j int) bool {
		return strings.Map(unicode.ToUpper, typeDefs[i].Ident.String()) < strings.Map(unicode.ToUpper, typeDefs[j].Ident.String())
	})

	for _, td := range typeDefs {
		f, err := os.OpenFile(filepath.Join(typeDir, fmt.Sprintf("%s.ts", td.Ident)), os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
		if err != nil {
			return fmt.Errorf("typegen file: %w", err)
		}
		var builder strings.Builder
		builder.WriteString("// Code generated by yaigo. DO NOT EDIT.\n")

		for _, std := range td.Properties {
			if std.Kind == Struct {
				builder.WriteString(fmt.Sprintf("import { type %s } from './%s'\n", std.Ident, std.Ident))
			}
		}

		builder.WriteString("\n")
		builder.WriteString(GenerateTypeDef(td, true))
		_, err = f.Write([]byte(builder.String()))
		if err != nil {
			f.Close()
			return fmt.Errorf("writing file: %w", err)
		}
		f.Close()
	}

	return nil
}
