package typegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func GenerateTypeDef(parent TsType) string {
	if parent.Kind != Object {
		panic("can only generate typedefs for objects")
	}
	types := parent.Properties
	var writer strings.Builder
	if parent.PkgPath != "" && parent.Name != "" {
		writer.WriteString(fmt.Sprintf("// from: %s/%s\n", parent.PkgPath, parent.Name))
	}
	if parent.export {
		writer.WriteString("export ")
	}
	writer.WriteString(fmt.Sprintf("type %s = {\n", parent.Ident))
	for _, v := range types {
		writer.WriteString("\t")
		writer.WriteString(v.PropertyName)
		if v.Optional {
			writer.WriteString("?")
		}
		writer.WriteString(": ")
		if v.Kind == Object {
			writer.WriteString(v.Ident.String())
		} else if v.Kind == Array {
			writer.WriteString(fmt.Sprintf("%s[]", v.Elem().Ident))
		} else if v.Kind == Map {
			writer.WriteString("{\n")
			writer.WriteString(fmt.Sprintf("\t\t[key: %s]: ", v.MapKey().Ident))
			writer.WriteString(v.Elem().Ident.String())
			if v.Elem().Optional {
				writer.WriteString(" | null")
			}
			writer.WriteString(";\n")
			writer.WriteString("\t}")
		} else if v.Kind == Primitive {
			writer.WriteString(v.Ident.String())
		} else {
			writer.WriteString("never")
		}
		writer.WriteString(";")
		if v.Comment != "" {
			writer.WriteString("// " + v.Comment)
		}
		writer.WriteString("\n")
	}

	writer.WriteString("}")
	writer.WriteString("\n")

	return writer.String()
}

func GenerateTypeScriptForComponent(typeDir string, root TsType) error {
	typeDefs := ExtractTypeDefs(root)

	for _, td := range typeDefs {
		f, err := os.OpenFile(filepath.Join(typeDir, fmt.Sprintf("%s.ts", td.Ident)), os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
		if err != nil {
			return fmt.Errorf("typegen file: %w", err)
		}
		var builder strings.Builder
		builder.WriteString("// Code generated by yaigo. DO NOT EDIT.\n")

		for _, std := range td.Properties {
			if std.Kind == Object {
				builder.WriteString(fmt.Sprintf("import { type %s } from './%s'\n", std.Ident, std.Ident))
			}
		}

		builder.WriteString("\n")
		td.Export(true)
		builder.WriteString(GenerateTypeDef(td))
		_, err = f.Write([]byte(builder.String()))
		if err != nil {
			f.Close()
			return fmt.Errorf("writing file: %w", err)
		}
		f.Close()
	}

	return nil
}
